# Generated by Django 3.0.1 on 2020-02-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsarcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='private',
            new_name='is_private',
        ),
    ]
