# Generated by Django 3.0.1 on 2020-02-23 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pollsarcapp', '0002_auto_20200220_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterModelOptions(
            name='polluser',
            options={'verbose_name': 'PollUser', 'verbose_name_plural': 'PollUser'},
        ),
        migrations.AlterModelOptions(
            name='proposition',
            options={'verbose_name': 'Proposition', 'verbose_name_plural': 'Propositions'},
        ),
        migrations.AlterModelOptions(
            name='propositionuser',
            options={'verbose_name': 'PropositionUser', 'verbose_name_plural': 'PropositionUser'},
        ),
        migrations.AddField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
